
export const formatDate = (
  dateString: string,
  locale: string = "en-US"
): string => {
  if (!dateString) return "";

  // Use regex or string split to extract parts
  const [year, month, day] = dateString.split("-").map(Number);
  if (!year || !month || !day) return dateString;

  // JS months are 0-indexed
  const date = new Date(year, month - 1, day);

  return new Intl.DateTimeFormat(locale, {
    year: "numeric",
    month: "long",
    day: "numeric",
  }).format(date);
};


export const BookCategories = [
  "athletes",
  "historical fiction",
  "science fiction",
  "fantasy",
  "mystery & thriller",
  "romance",
  "horror",
  "literary fiction",
  "biography & autobiography",
  "memoir",
  "self-help",
  "business & economics",
  "personal development",
  "psychology",
  "philosophy",
  "religion & spirituality",
  "true crime",
  "entrepreneurship",
  "finance",
  "investing",
  "marketing",
  "management & leadership",
  "programming",
  "data science",
  "cybersecurity",
  "software engineering",
  "artificial intelligence",
  "computers", 
  "study guides",
  "test preparation",
  "language learning",
  "dictionaries & thesauruses",
  "physics",
  "chemistry",
  "biology",
  "environment",
  "mathematics",
  "fitness",
  "nutrition",
  "mental health",
  "medicine",
  "art & design",
  "photography",
  "music",
  "crafts & diy",
  "graphic novels",
  "picture books",
  "early readers",
  "middle grade",
  "young adult fiction",
  "travel guides",
  "adventure memoirs",
  "geography & cultures",
  "world history",
  "military history",
  "political science",
  "social sciences",
  "fiction",
];

export const languageMap: Record<string, string> = {
  af: "Afrikaans",
  ar: "Arabic",
  az: "Azerbaijani",
  be: "Belarusian",
  bg: "Bulgarian",
  bn: "Bengali",
  bs: "Bosnian",
  ca: "Catalan",
  cs: "Czech",
  da: "Danish",
  de: "German",
  el: "Greek",
  en: "English",
  es: "Spanish",
  et: "Estonian",
  fa: "Persian",
  fi: "Finnish",
  fil: "Filipino",
  fr: "French",
  ga: "Irish",
  gu: "Gujarati",
  he: "Hebrew",
  hi: "Hindi",
  hr: "Croatian",
  hu: "Hungarian",
  hy: "Armenian",
  id: "Indonesian",
  is: "Icelandic",
  it: "Italian",
  ja: "Japanese",
  jv: "Javanese",
  ka: "Georgian",
  kk: "Kazakh",
  ko: "Korean",
  lt: "Lithuanian",
  lv: "Latvian",
  mk: "Macedonian",
  ml: "Malayalam",
  mn: "Mongolian",
  mr: "Marathi",
  ms: "Malay",
  nb: "Norwegian Bokmål",
  nl: "Dutch",
  pl: "Polish",
  pt: "Portuguese",
  ro: "Romanian",
  ru: "Russian",
  sk: "Slovak",
  sl: "Slovene",
  sr: "Serbian",
  sv: "Swedish",
  sw: "Swahili",
  ta: "Tamil",
  te: "Telugu",
  th: "Thai",
  tr: "Turkish",
  uk: "Ukrainian",
  ur: "Urdu",
  vi: "Vietnamese",
  zh: "Chinese"
};
