export const BookCategories = [
  "athletes",
  "historical fiction",
  "science fiction",
  "fantasy",
  "mystery & thriller",
  "romance",
  "horror",
  "literary fiction",
  "biography & autobiography",
  "memoir",
  "self-help",
  "business & economics",
  "personal development",
  "psychology",
  "philosophy",
  "religion & spirituality",
  "true crime",
  "entrepreneurship",
  "finance",
  "investing",
  "marketing",
  "management & leadership",
  "programming",
  "data science",
  "cybersecurity",
  "software engineering",
  "artificial intelligence",
  "computers", 
  "study guides",
  "test preparation",
  "language learning",
  "dictionaries & thesauruses",
  "physics",
  "chemistry",
  "biology",
  "environment",
  "mathematics",
  "fitness",
  "nutrition",
  "mental health",
  "medicine",
  "art & design",
  "photography",
  "music",
  "crafts & diy",
  "graphic novels",
  "picture books",
  "early readers",
  "middle grade",
  "young adult fiction",
  "travel guides",
  "adventure memoirs",
  "geography & cultures",
  "world history",
  "military history",
  "political science",
  "social sciences",
  "fiction",
];
